// <auto-generated />
namespace ESTAFF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class removeProfilePicturePath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeProfilePicturePath));
        
        string IMigrationMetadata.Id
        {
            get { return "202607270147037_removeProfilePicturePath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
